name: Reproduce
on: [push, workflow_dispatch]
defaults:
  run:
    shell: bash
jobs:
  reproduce:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fruit:
          - name: apple
            color: red
          - name: pear
            color: green
        animal:
          - name: cat
            sound: meow
          - name: dog
            sound: bark
        include:
          - fruit:
              name: banana
              color: yellow
            animal:
              name: cow
              sound: moo
    steps:
      - name: Print Matrix Values
        run: |
          echo "Fruit: ${{ matrix.fruit.name }} is ${{ matrix.fruit.color }}"
          echo "Animal: ${{ matrix.animal.name }} makes sound: ${{ matrix.animal.sound }}"
          echo "Matrix: ${{ toJson(matrix) }}"
